import order from "../../../assets/apple.svg";

const orders = [
  {
    order_key: 1,
    user_id: 1,
    business_name: "Business1",
    domain: "domain1.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 2,
    user_id: 1,
    business_name: "Business2",
    domain: "domain2.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 3,
    user_id: 1,
    business_name: "Business3",
    domain: "domain3.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 4,
    user_id: 1,
    business_name: "Business4",
    domain: "domain4.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 5,
    user_id: 1,
    business_name: "Business5",
    domain: "domain5.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 6,
    user_id: 1,
    business_name: "Business6",
    domain: "domain6.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 7,
    user_id: 1,
    business_name: "Business7",
    domain: "domain7.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 8,
    user_id: 1,
    business_name: "Business8",
    domain: "domain8.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 9,
    user_id: 1,
    business_name: "Business9",
    domain: "domain9.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 10,
    user_id: 1,
    business_name: "Business10",
    domain: "domain10.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 11,
    user_id: 1,
    business_name: "Business11",
    domain: "domain11.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 12,
    user_id: 1,
    business_name: "Business12",
    domain: "domain12.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 13,
    user_id: 1,
    business_name: "Business13",
    domain: "domain13.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 14,
    user_id: 1,
    business_name: "Business14",
    domain: "domain14.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 15,
    user_id: 1,
    business_name: "Business15",
    domain: "domain15.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 16,
    user_id: 2,
    business_name: "Business16",
    domain: "domain16.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 17,
    user_id: 2,
    business_name: "Business17",
    domain: "domain17.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 18,
    user_id: 2,
    business_name: "Business18",
    domain: "domain18.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 19,
    user_id: 2,
    business_name: "Business19",
    domain: "domain19.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 20,
    user_id: 2,
    business_name: "Business20",
    domain: "domain20.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 21,
    user_id: 2,
    business_name: "Business21",
    domain: "domain21.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 22,
    user_id: 2,
    business_name: "Business22",
    domain: "domain22.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 23,
    user_id: 2,
    business_name: "Business23",
    domain: "domain23.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 24,
    user_id: 2,
    business_name: "Business24",
    domain: "domain24.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 25,
    user_id: 2,
    business_name: "Business25",
    domain: "domain25.com",
    is_active: true,
    order_logo: order,
  },
  {
    order_key: 26,
    user_id: 2,
    business_name: "Business26",
    domain: "domain26.com",
    is_active: false,
    order_logo: order,
  },
  {
    order_key: 27,
    user_id: 2,
    business_name: "Business27",
    domain: "domain27.com",
    is_active: true,
    order_logo: order,
  },
];

export default orders;
